[package]
name = "mypkg"
version = "0.1.0"
edition = "2021"

[lib]
name = "mypkg"
crate-type = ["dylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
